
DROP TABLE VENDAITEM;
DROP TABLE VENDARECEITA;
DROP TABLE VENDADESCONTO;
DROP TABLE VENDA;
DROP TABLE CADPRODUTO;
DROP TABLE CADGRUPOPRODUTO;

CREATE TABLE CADGRUPOPRODUTO(
	CODIGO INTEGER NOT NULL,
	DESCRICAO VARCHAR(40) NOT NULL,
	CONSTRAINT PK_CADGRUPOPRODUTO PRIMARY KEY(CODIGO)
);

INSERT INTO CADGRUPOPRODUTO VALUES(1, 'Alimentos');
INSERT INTO CADGRUPOPRODUTO VALUES(2, 'Bebidas');
INSERT INTO CADGRUPOPRODUTO VALUES(3, 'Brindes');

CREATE TABLE CADPRODUTO(
	CODIGO INTEGER NOT NULL,
	DESCRICAO VARCHAR(40) NOT NULL,
	CODIGO_GRUPO INTEGER NOT NULL,
	VALOR NUMERIC(9,2) NOT NULL,
	CONSTRAINT PK_CADPRODUTO PRIMARY KEY(CODIGO),
	CONSTRAINT FK_PRODUTO_GRUPO FOREIGN KEY(CODIGO_GRUPO) REFERENCES CADGRUPOPRODUTO(CODIGO)
);

DELETE FROM CADPRODUTO;
INSERT INTO CADPRODUTO VALUES(1, 'Cerveja', 2, 4.5);
INSERT INTO CADPRODUTO VALUES(2, 'Água', 2, 2.0);
INSERT INTO CADPRODUTO VALUES(3, 'Refrigerante', 2, 4.0);
INSERT INTO CADPRODUTO VALUES(4, 'Chop', 2, 8.0);
INSERT INTO CADPRODUTO VALUES(5, 'Churrascada', 1, 99.9);
INSERT INTO CADPRODUTO VALUES(6, 'Porção de Torresmo', 1, 39.9);
INSERT INTO CADPRODUTO VALUES(7, 'Porção de Fritas', 1, 24.9);
INSERT INTO CADPRODUTO VALUES(8, 'Burgão da Casa', 1, 35.0);
INSERT INTO CADPRODUTO VALUES(9, 'Burgão Vegi (por sua conta em risco)', 1, 49.5);
INSERT INTO CADPRODUTO VALUES(10, 'Porção de mandioca frita', 1, 24.9);
INSERT INTO CADPRODUTO VALUES(11, 'Boné', 3, 30.5);
INSERT INTO CADPRODUTO VALUES(12, 'Chaveiro', 3, 10.5);
INSERT INTO CADPRODUTO VALUES(13, 'Poster', 3, 15.5);
INSERT INTO CADPRODUTO VALUES(14, 'Bandeira de Time', 3, 39.5);
INSERT INTO CADPRODUTO VALUES(15, 'Aparador de Copo', 3, 1.5);
INSERT INTO CADPRODUTO VALUES(16, 'Copo', 3, 9.5);

CREATE TABLE VENDA(
	CODIGO INTEGER NOT NULL,
	DATA TIMESTAMP NOT NULL,
	VALOR_BRUTO NUMERIC(9,2) NOT NULL,
	VALOR_DESCONTO NUMERIC(9,2) DEFAULT 0.0,
	VALOR_LIQUIDO NUMERIC(9,2) NOT NULL,
	CANCELADA VARCHAR(1) DEFAULT 'N',
	CONSTRAINT PK_VENDA PRIMARY KEY(CODIGO)
);

CREATE TABLE VENDAITEM(
	CODIGO_SEQUENCIAL INTEGER NOT NULL,
	CODIGO_VENDA INTEGER NOT NULL,
	CODIGO_PRODUTO INTEGER NOT NULL,
	VALOR NUMERIC(9,2) NOT NULL,
	QTDE INTEGER NOT NULL,
	VALOR_SUBTOTAL NUMERIC(9,2) NOT NULL,
	CONSTRAINT PK_VENDAITEM PRIMARY KEY(CODIGO_SEQUENCIAL, CODIGO_VENDA, CODIGO_PRODUTO),
	CONSTRAINT FK_ITEM_VENDA FOREIGN KEY(CODIGO_VENDA) REFERENCES VENDA(CODIGO),
	CONSTRAINT FK_ITEM_PRODUTO FOREIGN KEY(CODIGO_PRODUTO) REFERENCES CADPRODUTO(CODIGO)
);

CREATE TABLE VENDARECEITA(
	CODIGO_SEQUENCIAL INTEGER NOT NULL,
	CODIGO_VENDA INTEGER NOT NULL,
	CODIGO_RECEITA INTEGER NOT NULL,
	DESCRICAO_RECEITA VARCHAR(40) NOT NULL,
	VALOR NUMERIC(9,2) NOT NULL,
	CONSTRAINT PK_VENDARECEITA PRIMARY KEY(CODIGO_SEQUENCIAL, CODIGO_VENDA, CODIGO_RECEITA),
	CONSTRAINT FK_RECEITA_VENDA FOREIGN KEY(CODIGO_VENDA) REFERENCES VENDA(CODIGO) 
);

CREATE TABLE VENDADESCONTO(
	CODIGO_SEQUENCIAL INTEGER NOT NULL,
	CODIGO_VENDA INTEGER NOT NULL,
	CODIGO_DESCONTO INTEGER NOT NULL,
	DESCRICAO_DESCONTO VARCHAR(40) NOT NULL,
	VALOR_PERCENTUAL NUMERIC(9,2) NOT NULL,
	CONSTRAINT PK_VENDADESCONTO PRIMARY KEY(CODIGO_SEQUENCIAL, CODIGO_VENDA, CODIGO_DESCONTO),
	CONSTRAINT FK_DESCONTO_VENDA FOREIGN KEY(CODIGO_VENDA) REFERENCES VENDA(CODIGO)
);

SELECT * FROM VENDA v 